config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  root to: "pages#home"

  
  get "items/index", to: "items#index", as: "items_home"
  get "items/new", to: "items#new", as: "items"
  get "items/users_items", to: "items#user_items"
  post "items/new", to: "items#create"
  get "items/:id", to: "items#show", as: "item"
  get "items/:id/edit", to: "items#edit", as: "edit_item"
  patch "items/:id", to: "items#update"
  put "items/:id", to: "items#update"
  delete "items/:id", to: "items#delete", as: "delete"
  get "profiles/new", to: "profiles#new", as: "profiles"
  post "profiles/new", to: "profiles#create"
  get "profiles/:id/edit", to: "profiles#edit", as: "edit_profile"
  patch "profiles/:id", to: "profiles#update"
  put "profiles/:id", to: "profiles#update"
  get "profiles/:id", to: "profiles#show", as: "profile"
  get "pages/categories/:id", to: "pages#categories", as: "category"
  get "purchase/:id", to: "boughts#purchase", as: "purchase"
  get "purchase/confimation/item/:id", to: "items#buy"
  get "items/user/order_history", to: "items#order_history", as: "order_history"
  get "profile/finder", to: "profiles#finder"
  get "profile/found/:id", to: "profiles#found"
  get "profile/:zip", to: "profiles#found"
  get "profile/:city", to: "profiles#found"
  get "profile/:state", to: "profiles#found"
  get "profile/:country", to: "profiles#found"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :category


  #conditions
  enum condition: {"Used" => 1 , "New" =>2}

  #image
  has_one_attached :picture
end

app/models/profile.rb
class Profile < ApplicationRecord
    validates_uniqueness_of :username
    belongs_to :user
    has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :items
  has_many :profile
  has_one_attached :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boughts_controller.rb
class BoughtsController < ApplicationController
before_action :find_item, only: [:purchase, :update]

    def purchase
        
    end
# updates item to sold and changes user id to current user
    def updated
        @item = @item.update({user_id: current_user.id, sold: true})
    end

    private
# finds the item required
    def find_item
        @item = Item.find(params[:id])
    end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :form_dependencies, only: [:new, :edit, :create, :index]
  before_action :find_item, only: [:show, :edit, :update, :delete, :auth_user, :buy]
  before_action :auth_params, only: [:create, :update]
  before_action :auth_user, only: [:delete, :edit]
  before_action :find_profile, only: [:show, :order_history]

# show all Items that the database contains
  def index
    @items = Item.where(sold: false)
  end

# makes a new Item to be sent to create to post to database
  def new
    @item = Item.new
  end

# create and save a new item to database only allowing the params that the form used to be accepted to make it more secure
  def create
    @items = current_user.items.new(auth_params)
      if @items.save
        redirect_to "/items/index", notice: "Your item has been created successfully."
      else
        redirect_to "/items/new", alert: "Something went wrong with your item please try again."
      end
  end

# shows specific Item on screen by using the params to find correct item
  def show
  end

  def edit
  end
#finds the item of the current user is not sold which means its currently listed.
  def user_items
    @items = Item.where(user_id: current_user.id, sold: false)
  end

  def delete
    @item.destroy
    redirect_to "/items/index", notice: "Your item has been deleted."
  end

  def update
    @item.update(auth_params)
      if @item.save
        redirect_to "/items/index", notice: "Your item has been created successfully."
      else
        redirect_to "/items/index", alert: "Something went wrong with your item please try again."
      end
  end

  def buy
    @item.update({user_id: current_user.id, sold: true})
      if @item.save
        redirect_to "/items/index", notice: "You bought an item."
      else
        redirect_to "/items/index", alert: "Something went wrong please try again."
      end
  end
#finds Items that have been made sold as true allowing for the user to see past purchases
  def order_history
    @items = Item.where(user_id: current_user.id, sold: true)
  end


  private

# sets both variables for both conditions and catagory to be used in the partial form when creating or editing a new Item
  def form_dependencies
    @condition = Item.conditions.keys
    @categories = Category.all
  end

# set varible for finding a specific listing
  def find_item
    @item = Item.find(params[:id])
  end

# acccepted params for creating and updating for security.
  def auth_params
    (params.require(:item).permit(:name, :description, :condition, :category_id, :price, :picture))
  end

# prevent editing and deleting through params for unautherised users
  def auth_user
    if @item.user_id != current_user.id
      redirect_to "/items/index", alert: "Something went wrong please try again."
    end
  end
# find profile
    def find_profile
        @profile = Profile.find_by(user_id: current_user.id)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
before_action :variables, only: [:home, :categories]
    def home
    end

    def categories
        @item = Item.where(category_id: params[:id], sold: false)
    end

    private

    def variables
        @categories = Category.all  
    end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :auth_params, only: [:create, :update]
    before_action :find_profile, only: [:show, :edit, :update, :finder , :found]
    before_action :bought_stats, :listed_stats, only: [:show]

    def home
    end

    def new
        @profile = Profile.new
    end

    def create
        @profile = current_user.profile.new(auth_params)
        if @profile.save
            redirect_to "/items/index", notice: "Your profile has been created successfully."
        else
            redirect_to "/profiles/new", alert: "Something went wrong like Username already taken please try again."
        end
    end

    def finder

    end

    def found
        @profile = Profile.all
    end

    def show
    end

    def update
        @profile.update(auth_params)
            if @profile.save
                redirect_to "/profiles/:id", notice: "Your profile has been updated successfully."
            else
                redirect_to "/profiles/:id/edit", alert: "Something went wrong with your changes please try again."
            end
    end

    private

    def find_profile
        @profile = Profile.find_by(user_id: current_user.id)
    end

    def auth_params
        (params.require(:profile).permit(:username, :address, :address2, :city, :country, :state, :zip, :picture))
    end

    def bought_stats
        @bought = Item.where(user_id: current_user.id, sold: true)
    end

    def listed_stats
        @listed = Item.where(user_id: current_user.id, sold: false)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
protected

    def after_sign_up_path_for(resource)
        "/profiles/new"
    end

    def after_inactive_sign_up_path_for(resource)
        "/profiles/new"
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def alert_class(type)
        case type
        when "notice"
            return "success"
        when "alert"
            return "warning"
        when "error"
            return "danger"
        else
            return "dark"
        end
    end
end

app/helpers/boughts_helper.rb
module BoughtsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boughts/purchase.html.erb
<h1>Order Confimation for <%=@item.name%></h1>
<%#shows the product one last time before being confirmed ass bought by the user.%>
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px">
                <%if @item.picture.attached?%>
                    <%=image_tag @item.picture, alt: @item.name, class:"thumbnail card-img top"%>
                <%else%>
                    <%=image_tag "dice-img.jpg", alt: "dice", class:"thumbnail card-img top"%>
                <%end%>
        <span class="font-weight-bold"><%=@item.name%></span><span class="text-black-50">Seller: <%=@item.user.email%></span></div>
        </div>
        <div class="col-md-5 border-right">
            <div class="p-3 py-5">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h4 class="text-right">Item Details</h4>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12"><label class="labels">Name: <%=@item.name %></div>
                    <div class="col-md-12"><label class="labels">Condition: </label><%=@item.condition %></div>
                    <div class="col-md-12"><label class="labels">Price: <%=@item.price %></div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="p-3 py-5">
                    <a href="/items/index" class="mt-auto btn btn-info">Return to Marketplace</a>
                    <a href="/purchase/confimation/item/<%=@item.id%>" class="mt-auto btn btn-primary" >Confirm</a>
            </div>
        </div>
    </div>
</div>
</div>
</div>

app/views/boughts/update.html.erb
<h1>Thank you for your order</h1>
<a href="/items/index" class="mt-auto btn btn-info">Return to Marketplace</a>

app/views/items/_form.html.erb
<%=form_with model: @item, local: true do |f| %>
<div class="p-5 text-dark bg-light bg-light shadow-1-strong rounded mb-3">
<%# enter name of item to be created using bootstrap for styling%>
    <div class="form-group row">
        <label for="title3" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-5">
                <%=f.text_field :name, :required => true%>
            </div>
    </div>

<%# enter description of item to be created using bootstrap for styling%>
    <div class="form-group row">
        <label for="description3" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-5">
                <%=f.text_area :description, :required => true%>
            </div>
    </div>

<%# enter condition using radio buttons using bootstrap for styling%>
    <div class="form-group row">
        <label for="ccondition3" class="col-sm-2 col-form-label">Condition</label>
            <div class="col-sm-5">
                <%= f.radio_button :condition, "Used", :value => "Used"%>
                <%= f.label :condition_used, "Used"%>
                <%= f.radio_button :condition, "New", :value => "New", :required => true%>
                <%= f.label :condition_new, "New" %>
            </div>
    </div>

<%# making a drop down selection for which catagory will be selected using bootstrap for styling%>
    <div class="form-group row">
        <label for="title3" class="col-sm-2 col-form-label">Category</label>
            <div class="col-sm-5">
                <%=f.select :category_id, Category.pluck(:name, :id)%>
            </div>
    </div>
    
<%# enter price for Item in cents to be converted to dollar else where using bootstrap for styling%>
    <div class="form-group row">
        <label for="title3" class="col-sm-2 col-form-label">Price</label>
        <div class="col-sm-5">
                <%=f.number_field :price, value: number_to_currency(f.object.price.to_f, delimiter: '', unit: ''), step: :any, :required => true%>
            </div>
    </div>

<%# allowing picture upload using AWS S3 as cloud storage for application using bootstrap for styling%>
        <div class="form-group row">
        <label for="title3" class="col-sm-2 col-form-label">Image</label>
            <div class="col-sm-5">
                <%=f.file_field :picture, accept: "image/jpg, image/png, image/jpeg, image/gif"%>
            </div>
    </div>
    
<%# redirecting to another method to save to the database%>
    <%=f.submit%>

<%end%>
</div>

app/views/items/_item_card.html.erb
<div class="container">
    <div class= "row row-cols-sm-1 row-cols-ms-2 row-cols-lg-4">
        <%# making each card for total Items that are held within the database using bootstrap for styling and positioning also uses a if statment to know which infomation
        should be viewed on screen%>
        <%@items.each do |item|%>
            <%if current_user && current_user.id == item.user_id && item.sold == true%>
                <div class="col-4">
                    <%if item.picture.attached?%>
                        <%=image_tag item.picture, alt: item.name, class:"thumbnail card-img top"%>
                    <%else%>
                        <%=image_tag "dice-img.jpg", alt: "dice", class:"thumbnail card-img top"%>
                    <%end%>
                        <div class="card-body mb-3 bg-light">
                            <h5 class="card-title"><%=item.name%></h5>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item">Owner: <%=@profile.username%></li> 
                                </ul>
                        <div class="card-body mb-3 bg-light">
                            <a href="/items/<%=item.id%>"class="mt-auto btn btn-warning">View Purchase</a>
                        </div>
                    </div>
                </div>
            <%else%>
                <div class="col-4">
                    <%if item.picture.attached?%>
                        <%=image_tag item.picture, alt: item.name, class:"thumbnail card-img top"%>
                    <%else%>
                        <%=image_tag "dice-img.jpg", alt: "dice", class:"thumbnail card-img top"%>
                    <%end%>
                        <div class="card-body mb-3 bg-light">
                            <h5 class="card-title"><%=item.name%></h5>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item">Condition: <%=item.condition%></li>
                                    <li class="list-group-item">Price: <%=number_to_currency(item.price, precision: 2)%> AUD</li>  
                                </ul>
                        <div class="card-body mb-3 bg-light">
                            <%if current_user && current_user.id%>
                                <div class="card-body mb-3 bg-light">
                                    <a href="/items/<%=item.id%>"class="mt-auto btn btn-warning">View</a>
                                </div>
                            <%else%>
                                <div class="card-body mb-3 bg-light">
                                    <a class="btn btn-success" <%= link_to "Sign Up to Buy", new_user_registration_path, class: "nav-link"%></a>
                                </div>
                            <%end%>
                        </div>
                    </div>
                </div>
            <%end%>
        <%end%>
    </div>
</div>

app/views/items/edit.html.erb
<h1 class="p-5 text-center text-white shadow-1-strong rounded mb-3">Edit Item</h1>

<%# able to edit the database entry with updated info%>
<%= render "form" %>

app/views/items/index.html.erb
<h1 class="p-5 text-light shadow-1-strong rounded mb-3">Items List</h1>

<%=form_with model: @item, local: true do |f| %>
    <div class="p-1 text-light text-center shadow-1-strong rounded mb-1">
        <h3>Filter items by Category</h3>
            <%@categories.each do |category|%>
                <a href="/pages/categories/<%=category.id%>"class="btn btn-primary btn-sm"><%=category.name%></a>
            <%end%>
    </div> 
<%end%>

<%#using the item card partial to render item cards %>
<%= render "item_card" %>

app/views/items/new.html.erb
<h1 class="p-5 text-light shadow-1-strong rounded mb-3">New Item</h1>

<%#using the form partial to show the form used to create a new Item %>
<%= render "form" %>

app/views/items/order_history.html.erb
<h1 class="p-5 text-light shadow-1-strong rounded mb-3">Order history</h1>
    <div class="p-1 text-light text-center shadow-1-strong rounded mb-1">
        <a href="/profiles/:id"class="btn btn-danger btn-lg">Back</a>
    </div>
<%#using the item card partial to render item cards %>
<%= render "item_card" %>

app/views/items/show.html.erb
<%# modifying a bootstrap templete to suit displaying a single item on screen when selected with a image carousel%>
<div class="container py-3">
    <div class="title h1 text-center"><%=@item.name%></div>
<!-- Card Start -->
        <div class="card">
            <div class="row ">
                <div class="col-md-7 px-3">
                    <div class="card-block px-6">
                        <h2 class="card-title"><%=@item.name%></h2>
                        <p class="card-text">
                            <%=@item.description%>
                        </p>
                    <div>
                        <li>Condition: <%=@item.condition%></li>
                        <li>Price: <%=number_to_currency(@item.price, precision: 2)%></li> 
                        <li>Category: <%=@item.category.name%></li>
                </div>
            <div class="mb-4">
<%# Checking if the current user is the same as the items creator to see if they can edit the listing or not%>
                <%if current_user && current_user.id == @item.user_id && @item.sold == false%>
                    <%= link_to "Edit", edit_item_path, class: "mt-auto btn btn-warning"%>
                    <%= link_to "Delete", @items, method: :delete, data: {confirm: "Are you sure?"}, class: "mt-auto btn btn-dark"%>
                    <%= link_to "Back", items_home_path, class: "mt-auto btn btn-danger"%>

                <%elsif current_user && current_user.id == @item.user_id && @item.sold == true%>
                    <%= link_to "Back", order_history_path, class: "mt-auto btn btn-danger"%>

                <%else%>
                    <%= link_to "Buy Now", purchase_path, class: "mt-auto btn btn-primary"%>
                    <%= link_to "Back", items_home_path, class: "mt-auto btn btn-danger"%>
                <%end%>
            </div>
        
        </div>
    </div>
<%# Bootstrap used for the carousel images. not my code used from free bootstrap templet site%>
    <!-- Carousel start -->
    <div class="col-md-5">
        <div id="CarouselTest" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#CarouselTest" data-slide-to="0" class="active"></li>
                <li data-target="#CarouselTest" data-slide-to="1"></li>
                <li data-target="#CarouselTest" data-slide-to="2"></li>
            </ol>
        <div class="carousel-inner">
            <div class="carousel-item active ">
                <%if @item.picture.attached?%>
                    <%=image_tag @item.picture, alt: @item.name, class:"d-block w-100 p-3 h-75 p-3"%>
                <%else%>
                    <%=image_tag "dice-img.jpg", alt: "dice", class:"d-block w-100 p-3 h-75 p-3"%>
                <%end%>
            </div>

            <div class="carousel-item">
                <%if @item.picture.attached?%>
                    <%=image_tag @item.picture, alt: @item.name, class:"d-block w-100 p-3 h-75 p-3"%>
                <%else%>
                    <%=image_tag "dice-img.jpg", alt: "dice", class:"d-block w-100 p-3 h-75 p-3"%>
                <%end%>
            </div>

            <div class="carousel-item">
                <%if @item.picture.attached?%>
                    <%=image_tag @item.picture, alt: @item.name, class:"d-block w-100 p-3 h-75 p-3"%>
                <%else%>
                    <%=image_tag "dice-img.jpg", alt: "dice", class:"d-block w-100 p-3 h-75 p-3"%>
                <%end%>
            </div>

                <a class="carousel-control-prev" href="#CarouselTest" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span> </a>
                <a class="carousel-control-next" href="#CarouselTest" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span></a>
                </div>
            </div>
        </div>
    <!-- End of carousel -->
    </div>
</div>
<!-- End of card -->

app/views/items/user_items.html.erb
<h1 class="p-5 text-light shadow-1-strong rounded mb-3">Your Current Listed Items</h1>

<%#using the item card partial to render item cards %>
<%= render "item_card" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>HomebrewAdventures</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body class="bg-secondary">



    <%flash.each do |type, msg|%>
      <div class="alert alert-<%=alert_class(type)%> alert-dismissable fade show" role="alert">
        <%=msg%>
        <button type="button" class="close" data-dismiss="alert" aria-label="close"> <span aria-hidden="true">&times;</span> </button>
      </div>
    <%end%>

    <%= render "shared/navbar"%>

    <%= yield %>

  </body>
</html>

app/views/pages/categories.html.erb
<h1 class="p-5 text-light shadow-1-strong rounded mb-3">Listed Items</h1>

    <div class="p-1 text-light text-center shadow-1-strong rounded mb-1">
        <h3>Back to All items</h3>
            <a href="/items/index"class="btn btn-danger btn-lg">Back</a>
    </div>

<div class="container">
    <div class= "row row-cols-sm-1 row-cols-ms-2 row-cols-lg-4">
        <%# making each card for total Items that are held within the database using bootstrap for styling and positioning%>
            <%@item.each do |item|%>
            <div class="col-4 ">
                <%if item.picture.attached?%>
                    <%=image_tag item.picture, alt: item.name, class:"thumbnail card-img top"%>
                <%else%>
                    <%=image_tag "dice-img.jpg", alt: "dice", class:"thumbnail card-img top"%>
                <%end%>
        <div class="card-body mb-3 bg-light">
            <h5 class="card-title"><%=item.name%></h5>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Condition: <%=item.condition%></li>
                    <li class="list-group-item">Price: <%=item.price%></li>    
                </ul>
                <%if current_user && current_user.id%>
                    <div class="card-body mb-3 bg-light">
                        <a href="/items/<%=item.id%>"class="mt-auto btn btn-warning">View</a>
                    </div>
                <%else%>
                    <div class="card-body mb-3 bg-light">
                        <a class="btn btn-success" <%= link_to "Sign Up to Buy", new_user_registration_path, class: "nav-link"%>></a>
                    </div>
                <%end%>
            </div>
        </div>
    <%end%>
</div>

app/views/pages/home.html.erb
<div class="bg-image p-5 text-center text-black shadow-1-strong rounded mb-3">
  <h1 class="mb-10 h1">Welcome to Homebrew Adventures DnD Marketplace</h1>
    <h2> If you have already please make an account if you would like to buy and sell on this platform.</h2>
    <h2> To check out the different Categories below or view the whole marketplace.</h2>
      <p class="lead">
      <%#allows the user to view the entire list of items currently for sale%>
        <a class="btn btn-primary btn-lg" href="items/index" role="button">Enter Marketplace</a>
      </p>
</div>
<%#Shows all categories to the user on the page so they are able to select which category they would like to view first%>
<div class="container">
  <div class="card-deck">
    <%@categories.each do |category|%>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card-body mb-3 bg-light">
          <div class="view overlay">
            <%=image_tag "dice-img.jpg", alt: "dice", class:"thumbnail card-img top"%>
            <a href="/pages/categories/<%=category.id%>">
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>

    <div class="card-body">
      <h4 class="card-title"><%=category.name%></h4>
        <p class="card-text">"Find it all here"</p>
        <a href="/pages/categories/<%=category.id%>"class="btn btn-primary btn-lg">View</a>
      </div>
    </div>
  </div>
<%end%>

app/views/profiles/_form.html.erb
<%=form_with model: @profile, local: true do |f| %>
<div class="p-5 text-dark bg-light bg-light shadow-1-strong rounded mb-3">
    <div class="form-group row">
        <label for="title3" class="col-sm-2 col-form-label">Username: </label>
            <div class="col-sm-5">
                <%=f.text_field :username, placeholder: "Username", :required => true%>
            </div>
    </div>

    <div class="form-group row">
        <label for="title3" class="col-sm-2 col-form-label">Address: </label>
            <div class="col-sm-5">
                <%=f.text_field :address, placeholder: "123 Main st", :required => true%>
            </div>
    </div>

    <div class="form-group row">
        <label for="title3" class="col-sm-2 col-form-label">Address: </label>
            <div class="col-sm-5">
                <%=f.text_field :address2, placeholder: "Apartment, studio, or floor"%>
            </div>
    </div>

    <div class="form-group row">
        <label for="title3" class="col-sm-2 col-form-label">City: </label>
            <div class="col-sm-5">
                <%=f.text_field :city, placeholder: "Sydney", :required => true%>
            </div>
    </div>

    <div class="form-group row">
        <label for="title3" class="col-sm-2 col-form-label">State: </label>
            <div class="col-sm-5">
                <%=f.text_field :state, placeholder: "NSW", :required => true%>
            </div>
    </div>

    <div class="form-group row">
        <label for="title3" class="col-sm-2 col-form-label">Zip: </label>
            <div class="col-sm-5">
                <%=f.text_field :zip, placeholder: "1234", :required => true, max: 4, min: 4%>
            </div>
    </div>

    <div class="form-group row">
        <label for="title3" class="col-sm-2 col-form-label">Country: </label>
            <div class="col-sm-5">
                <%=f.text_field :country, placeholder: "Country", :required => true%>
            </div>
    </div>

    <div class="form-group row">
        <label for="title3" class="col-sm-2 col-form-label">Profile Picture</label>
            <div class="col-sm-5">
                <%=f.file_field :picture, accept: "image/jpg, image/png, image/jpeg, image/gif"%>
            </div>
    </div>
</div>

    <%=f.submit%>
    
<%end%>
</div>

app/views/profiles/edit.html.erb
<h1 class="p-5 text-light shadow-1-strong rounded mb-3">Edit profile</h1>


<%= render "form" %>

app/views/profiles/found.html.erb
<h1 class="p-5 text-light shadow-1-strong rounded mb-3">People near you</h1>

<div class="container">
    <div class= "row row-cols-sm-1 row-cols-ms-2 row-cols-lg-4">
        <%# making each card for total Items that are held within the database using bootstrap for styling and positioning%>
        <%@profile.each do |profile|%>
            <div class="col-4">
                <%if profile.picture.attached?%>
                    <%=image_tag profile.picture, alt: profile.username, class:"thumbnail card-img top"%>
                <%else%>
                    <%=image_tag "profile-img.jpg", alt: "default-image", class:"thumbnail card-img top"%>
                <%end%>
                    <div class="card-body mb-3 bg-light">
                        <h5 class="card-title">Username: <%=profile.username%></h5>
                            <ul class="list-group list-group-flush">
                                    <div class="stats">
                                <a href="/profile/<%=profile.id%>"class="mt-auto btn btn-primary">Contact</a>
                            </ul>
                    </div>
            </div>
        <%end%>
    </div>
</div>

app/views/profiles/new.html.erb
<h1 class="p-5 text-light shadow-1-strong rounded mb-3">New Profile</h1>


<%= render "form" %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand btn btn-outline-success" href="/">Homebrew-Adventures</a>
  <form class="form-inline">
  <%if user_signed_in?%>
      <a class="btn btn-outline-primary"<%=link_to "Profile", "/profiles/:id", class: "nav-link" %></a>
      <a class="btn btn-outline-info" <%=link_to "Sell Item", items_path, class: "nav-link"%></a>
        <div style="padding-left: 5px;">
          <a class="btn btn-outline-danger"<%=link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link"%></a>
        </div>
    <%else%>
      <a class="btn btn-outline-primary" <%= link_to "Log In", new_user_session_path, class: "nav-link"%></a>
        <div style="padding-left: 10px;">
          <a class="btn btn-outline-success" <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"%></a>
        </div>    
  <%end%>
  </form>
</nav>